- hosts: servers
  become: yes
  vars:
    postgresql_version:
      series: 12
    users:
      - benchmark
  tasks:
    # Base
    # - name: Upgrade packages
    #   dnf:
    #     name: "*"
    #     state: latest
    #     enablerepo:
    #       - powertools
    - name: Install epel-release on Red Hat Enterprise Linux
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      when: ansible_distribution == "RedHat"
    - name: Install packages
      dnf:
        name:
          - git
          - bzip2
          - xz
          - ruby
          - rubygem-bundler
          - vim

    # Users
    - name: Create users
      user:
        name: "{{ item }}"
      with_items: "{{ users }}"

    # PGroonga
    - name: Add PostgreSQL YUM repository
      dnf:
        name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
        disable_gpg_check: true
    - name: Add PGroonga YUM repository
      dnf:
        name: "https://packages.groonga.org/almalinux/8/groonga-release-latest.noarch.rpm"
        disable_gpg_check: true
    - name: Disable PostgreSQL module
      shell: |
        dnf -y module disable postgresql
    - name: Install PostgreSQL
      dnf:
        name: postgresql{{ postgresql_version.series }}-server
      register: install_postgresql
    - name: Initialize PostgreSQL database
      shell: |
        /usr/pgsql-{{ postgresql_version.series }}/bin/postgresql-{{ postgresql_version.series }}-setup initdb
      when: install_postgresql.changed
    - name: Enable PostgreSQL
      systemd:
        name: postgresql-{{ postgresql_version.series }}
        enabled: true
    - name: Accept replication connections from almalinux-8-standby
      lineinfile:
        path: /var/lib/pgsql/{{ postgresql_version.series }}/data/pg_hba.conf
        regexp: "^host replication replicator"
        line: "host replication replicator 192.168.56.12/32 md5"
      notify:
        - Restart PostgreSQL
    - name: Enable additional PostgreSQL configurations
      lineinfile:
        path: /var/lib/pgsql/{{ postgresql_version.series }}/data/postgresql.conf
        regexp: "^include_dir ="
        line: "include_dir = 'postgresql.conf.d'"
      notify:
        - Restart PostgreSQL
    - name: Install PGroonga
      dnf:
        name:
          - postgresql{{ postgresql_version.series }}-pgdg-pgroonga
          - groonga
        enablerepo:
          - powertools
    - name: Create additional PostgreSQL configurations directory
      file:
        path: /var/lib/pgsql/{{ postgresql_version.series }}/data/postgresql.conf.d/
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"
    - name: Put additional PostgreSQL configurations
      copy:
        src: var/lib/pgsql/{{ postgresql_version.series }}/data/postgresql.conf.d/{{ item }}
        dest: /var/lib/pgsql/{{ postgresql_version.series }}/data/postgresql.conf.d/{{ item }}
        owner: postgres
        group: postgres
        mode: "0700"
      with_items:
        - pgroonga.conf
        - replication.conf
      notify:
        - Restart PostgreSQL
    - name: Set vm.overcomit_memory to 1
      copy:
        src: etc/sysctl.d/groonga.conf
        dest: /etc/sysctl.d/groonga.conf
        mode: 0755
        owner: root
        group: root
      notify:
        - Apply sysctl
    - name: Ensure starting PostgreSQL
      systemd:
        name: postgresql-{{ postgresql_version.series }}
        state: started
    - name: Check vagrant user
      become_user: postgres
      shell: |
        psql \
          --no-align \
          --tuples-only \
          --command="SELECT * FROM pg_user WHERE usename = 'vagrant'"
      args:
        chdir: ~postgres
      vars:
        ansible_ssh_pipelining: true
      register:
        postgresql_vagrant_user
    - name: Create vagrant user
      become_user: postgres
      shell: |
        psql \
          --no-align \
          --tuples-only \
          --command="CREATE ROLE vagrant WITH SUPERUSER LOGIN"
      args:
        chdir: ~postgres
      vars:
        ansible_ssh_pipelining: true
      when: postgresql_vagrant_user.stdout == ""
    - name: Check replication user
      become_user: postgres
      shell: |
        psql \
          --no-align \
          --tuples-only \
          --command="SELECT * FROM pg_user WHERE usename = 'replicator'"
      args:
        chdir: ~postgres
      vars:
        ansible_ssh_pipelining: true
      register:
        postgresql_replication_user
    - name: Create replication user
      become_user: postgres
      shell: |
        psql \
          --no-align \
          --tuples-only \
          --command="CREATE ROLE replicator WITH LOGIN REPLICATION PASSWORD 'passw0rd'"
      args:
        chdir: ~postgres
      vars:
        ansible_ssh_pipelining: true
      when: postgresql_replication_user.stdout == ""

    # Ruby libraries
    - name: Install Ruby libraries
      become_user: vagrant
      bundler:
        user_install: false
        chdir: /vagrant
      vars:
        ansible_ssh_pipelining: true

  handlers:
    - name: Apply sysctl
      command: sysctl --system
    - name: Restart PostgreSQL
      systemd:
        name: postgresql-{{ postgresql_version.series }}
        state: restarted
